version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: sql_server
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
  client:
    build:
      context: ./nuxtjs
      dockerfile: ./DockerFile
    command: npm run dev
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nuxtjs:/myapp
    depends_on:
      - mysql
  strapi:
    build: ./strapi
    command: yarn develop
    tty: true
    restart: always
    tty: true
    ports:
      - "1337:1337"
    volumes: 
      - ./strapi:/strapi
    depends_on:
      - mysql
