version: "3"
services:
  postgres:
    image: postgres:10-alpine
    container_name: "test-postgres-db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    image: node:12.8
    ports:
      - "0.0.0.0:1337:1337"
    volumes:
      - ./app:/src
    working_dir: /src
    tty: true
    command: npm run develop
    depends_on:
      - postgres
  client:
    build:
      context: ./nuxtjs
      dockerfile: ./DockerFile
    command: npm run dev
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nuxtjs:/myapp
    depends_on:
      - app
